# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
 
# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: oparm_base__oparm_link01
  pid: {p: 700.0, i: 50, d: 70.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: oparm_link01__oparm_link02
  pid: {p: 600.0, i: 50, d: 70.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: oparm_link02__oparm_link03
  pid: {p: 20000.0, i: 50, d: 1000.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: oparm_link03__oparm_link04
  pid: {p: 2000.0, i: 50, d: 200.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: oparm_link04__oparm_link05
  pid: {p: 700.0, i: 50, d: 70.0}
